/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0-beta.9.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface InspectionPhoto {
    id: string;
    externalBlob: ExternalBlob;
    annotations: Array<Annotation>;
    aiAnalysisResults: Array<AIAnalysisResult>;
    aiCaption?: string;
    defectDescription?: string;
}
export interface Address {
    zip: string;
    street: string;
    city: string;
    state: string;
}
export interface InspectionInput {
    tier: SubscriptionTier;
    inspectorId: Principal;
    propertyDetails?: PropertyDetails;
    address: Address;
}
export interface TransformationOutput {
    status: bigint;
    body: Uint8Array;
    headers: Array<http_header>;
}
export type Time = bigint;
export interface Inspection {
    id: string;
    startTime: Time;
    status: InspectionStatus;
    endTime?: Time;
    subscriptionTier: SubscriptionTier;
    inspectorId: Principal;
    propertyDetails?: PropertyDetails;
    summary: string;
    address: Address;
    aiAnalysisOngoing: boolean;
    rooms: Array<Room>;
}
export interface _CaffeineStorageRefillInformation {
    proposed_top_up_amount?: bigint;
}
export interface DefectInput {
    defect: Defect;
    roomId: string;
}
export interface Room {
    id: string;
    name: string;
    defects: Array<Defect>;
    photos: Array<InspectionPhoto>;
}
export interface _CaffeineStorageCreateCertificateResult {
    method: string;
    blob_hash: string;
}
export interface Annotation {
    id: bigint;
    color: string;
    text?: string;
    timestamp: bigint;
    annotationType: string;
    coordinates: Array<bigint>;
}
export interface PropertyDetails {
    bedrooms: bigint;
    squareFootage: bigint;
    bathrooms: bigint;
    yearBuilt: bigint;
}
export interface http_header {
    value: string;
    name: string;
}
export interface http_request_result {
    status: bigint;
    body: Uint8Array;
    headers: Array<http_header>;
}
export interface Defect {
    id: string;
    recommendations: Array<string | null>;
    description: string;
    severity: string;
    imageId: string;
}
export interface AIAnalysisResult {
    defectType: string;
    description: string;
    severityRating: string;
    confidence: string;
}
export interface ShoppingItem {
    productName: string;
    currency: string;
    quantity: bigint;
    priceInCents: bigint;
    productDescription: string;
}
export interface RoomInput {
    roomId: string;
    inspectionId: string;
    roomName: string;
}
export interface TransformationInput {
    context: Uint8Array;
    response: http_request_result;
}
export type StripeSessionStatus = {
    __kind__: "completed";
    completed: {
        userPrincipal?: string;
        response: string;
    };
} | {
    __kind__: "failed";
    failed: {
        error: string;
    };
};
export interface StripeConfiguration {
    allowedCountries: Array<string>;
    secretKey: string;
}
export interface _CaffeineStorageRefillResult {
    success?: boolean;
    topped_up_amount?: bigint;
}
export interface UserProfile {
    contactInfo: string;
    name: string;
    email: string;
    companyLogo?: string;
    companyName: string;
}
export enum InspectionStatus {
    completed = "completed",
    draft = "draft",
    inProgress = "inProgress",
    reportGenerated = "reportGenerated"
}
export enum SubscriptionTier {
    premium = "premium",
    free = "free"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _caffeineStorageBlobIsLive(hash: Uint8Array): Promise<boolean>;
    _caffeineStorageBlobsToDelete(): Promise<Array<Uint8Array>>;
    _caffeineStorageConfirmBlobDeletion(blobs: Array<Uint8Array>): Promise<void>;
    _caffeineStorageCreateCertificate(blobHash: string): Promise<_CaffeineStorageCreateCertificateResult>;
    _caffeineStorageRefillCashier(refillInformation: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult>;
    _caffeineStorageUpdateGatewayPrincipals(): Promise<void>;
    addRoomToInspection(roomInput: RoomInput): Promise<void>;
    analyzePhoto(roomId: string, photoId: string): Promise<AIAnalysisResult>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    createCheckoutSession(items: Array<ShoppingItem>, successUrl: string, cancelUrl: string): Promise<string>;
    createInspection(input: InspectionInput): Promise<string>;
    deleteDefect(roomId: string, defectId: string): Promise<void>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getDefectsForRoom(roomId: string): Promise<Array<Defect>>;
    getInspection(inspectionId: string): Promise<Inspection | null>;
    getPropertyDetails(inspectionId: string): Promise<PropertyDetails | null>;
    getRoom(roomId: string): Promise<Room>;
    getRoomsWithPhotos(inspectionId: string): Promise<Array<Room>>;
    getRoomsWithoutPhotos(inspectionId: string): Promise<Array<Room>>;
    getStats(): Promise<Array<[string, bigint]>>;
    getStripeSessionStatus(sessionId: string): Promise<StripeSessionStatus>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    initializeAccessControl(): Promise<void>;
    isCallerAdmin(): Promise<boolean>;
    isStripeConfigured(): Promise<boolean>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    setStripeConfiguration(config: StripeConfiguration): Promise<void>;
    transform(input: TransformationInput): Promise<TransformationOutput>;
    updateDefect(defectInput: DefectInput): Promise<void>;
    uploadPhoto(roomId: string, photoId: string, blob: ExternalBlob): Promise<void>;
}
import type { AIAnalysisResult as _AIAnalysisResult, Address as _Address, Annotation as _Annotation, Defect as _Defect, DefectInput as _DefectInput, ExternalBlob as _ExternalBlob, Inspection as _Inspection, InspectionInput as _InspectionInput, InspectionPhoto as _InspectionPhoto, InspectionStatus as _InspectionStatus, PropertyDetails as _PropertyDetails, Room as _Room, StripeSessionStatus as _StripeSessionStatus, SubscriptionTier as _SubscriptionTier, Time as _Time, UserProfile as _UserProfile, UserRole as _UserRole, _CaffeineStorageRefillInformation as __CaffeineStorageRefillInformation, _CaffeineStorageRefillResult as __CaffeineStorageRefillResult } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _caffeineStorageBlobIsLive(arg0: Uint8Array): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobIsLive(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobIsLive(arg0);
            return result;
        }
    }
    async _caffeineStorageBlobsToDelete(): Promise<Array<Uint8Array>> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobsToDelete();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobsToDelete();
            return result;
        }
    }
    async _caffeineStorageConfirmBlobDeletion(arg0: Array<Uint8Array>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
            return result;
        }
    }
    async _caffeineStorageCreateCertificate(arg0: string): Promise<_CaffeineStorageCreateCertificateResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageCreateCertificate(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageCreateCertificate(arg0);
            return result;
        }
    }
    async _caffeineStorageRefillCashier(arg0: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this.uploadFile, this.downloadFile, arg0));
                return from_candid__CaffeineStorageRefillResult_n4(this.uploadFile, this.downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this.uploadFile, this.downloadFile, arg0));
            return from_candid__CaffeineStorageRefillResult_n4(this.uploadFile, this.downloadFile, result);
        }
    }
    async _caffeineStorageUpdateGatewayPrincipals(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
            return result;
        }
    }
    async addRoomToInspection(arg0: RoomInput): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addRoomToInspection(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addRoomToInspection(arg0);
            return result;
        }
    }
    async analyzePhoto(arg0: string, arg1: string): Promise<AIAnalysisResult> {
        if (this.processError) {
            try {
                const result = await this.actor.analyzePhoto(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.analyzePhoto(arg0, arg1);
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n8(this.uploadFile, this.downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n8(this.uploadFile, this.downloadFile, arg1));
            return result;
        }
    }
    async createCheckoutSession(arg0: Array<ShoppingItem>, arg1: string, arg2: string): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.createCheckoutSession(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createCheckoutSession(arg0, arg1, arg2);
            return result;
        }
    }
    async createInspection(arg0: InspectionInput): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.createInspection(to_candid_InspectionInput_n10(this.uploadFile, this.downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createInspection(to_candid_InspectionInput_n10(this.uploadFile, this.downloadFile, arg0));
            return result;
        }
    }
    async deleteDefect(arg0: string, arg1: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteDefect(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteDefect(arg0, arg1);
            return result;
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n14(this.uploadFile, this.downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n14(this.uploadFile, this.downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n18(this.uploadFile, this.downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n18(this.uploadFile, this.downloadFile, result);
        }
    }
    async getDefectsForRoom(arg0: string): Promise<Array<Defect>> {
        if (this.processError) {
            try {
                const result = await this.actor.getDefectsForRoom(arg0);
                return from_candid_vec_n20(this.uploadFile, this.downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getDefectsForRoom(arg0);
            return from_candid_vec_n20(this.uploadFile, this.downloadFile, result);
        }
    }
    async getInspection(arg0: string): Promise<Inspection | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getInspection(arg0);
                return from_candid_opt_n24(this.uploadFile, this.downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getInspection(arg0);
            return from_candid_opt_n24(this.uploadFile, this.downloadFile, result);
        }
    }
    async getPropertyDetails(arg0: string): Promise<PropertyDetails | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getPropertyDetails(arg0);
                return from_candid_opt_n32(this.uploadFile, this.downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPropertyDetails(arg0);
            return from_candid_opt_n32(this.uploadFile, this.downloadFile, result);
        }
    }
    async getRoom(arg0: string): Promise<Room> {
        if (this.processError) {
            try {
                const result = await this.actor.getRoom(arg0);
                return from_candid_Room_n34(this.uploadFile, this.downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getRoom(arg0);
            return from_candid_Room_n34(this.uploadFile, this.downloadFile, result);
        }
    }
    async getRoomsWithPhotos(arg0: string): Promise<Array<Room>> {
        if (this.processError) {
            try {
                const result = await this.actor.getRoomsWithPhotos(arg0);
                return from_candid_vec_n33(this.uploadFile, this.downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getRoomsWithPhotos(arg0);
            return from_candid_vec_n33(this.uploadFile, this.downloadFile, result);
        }
    }
    async getRoomsWithoutPhotos(arg0: string): Promise<Array<Room>> {
        if (this.processError) {
            try {
                const result = await this.actor.getRoomsWithoutPhotos(arg0);
                return from_candid_vec_n33(this.uploadFile, this.downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getRoomsWithoutPhotos(arg0);
            return from_candid_vec_n33(this.uploadFile, this.downloadFile, result);
        }
    }
    async getStats(): Promise<Array<[string, bigint]>> {
        if (this.processError) {
            try {
                const result = await this.actor.getStats();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getStats();
            return result;
        }
    }
    async getStripeSessionStatus(arg0: string): Promise<StripeSessionStatus> {
        if (this.processError) {
            try {
                const result = await this.actor.getStripeSessionStatus(arg0);
                return from_candid_StripeSessionStatus_n43(this.uploadFile, this.downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getStripeSessionStatus(arg0);
            return from_candid_StripeSessionStatus_n43(this.uploadFile, this.downloadFile, result);
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n14(this.uploadFile, this.downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n14(this.uploadFile, this.downloadFile, result);
        }
    }
    async initializeAccessControl(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.initializeAccessControl();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.initializeAccessControl();
            return result;
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async isStripeConfigured(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isStripeConfigured();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isStripeConfigured();
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(to_candid_UserProfile_n46(this.uploadFile, this.downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(to_candid_UserProfile_n46(this.uploadFile, this.downloadFile, arg0));
            return result;
        }
    }
    async setStripeConfiguration(arg0: StripeConfiguration): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.setStripeConfiguration(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setStripeConfiguration(arg0);
            return result;
        }
    }
    async transform(arg0: TransformationInput): Promise<TransformationOutput> {
        if (this.processError) {
            try {
                const result = await this.actor.transform(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.transform(arg0);
            return result;
        }
    }
    async updateDefect(arg0: DefectInput): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateDefect(to_candid_DefectInput_n48(this.uploadFile, this.downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateDefect(to_candid_DefectInput_n48(this.uploadFile, this.downloadFile, arg0));
            return result;
        }
    }
    async uploadPhoto(arg0: string, arg1: string, arg2: ExternalBlob): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.uploadPhoto(arg0, arg1, await to_candid_ExternalBlob_n54(this.uploadFile, this.downloadFile, arg2));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.uploadPhoto(arg0, arg1, await to_candid_ExternalBlob_n54(this.uploadFile, this.downloadFile, arg2));
            return result;
        }
    }
}
function from_candid_Annotation_n41(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Annotation): Annotation {
    return from_candid_record_n42(uploadFile, downloadFile, value);
}
function from_candid_Defect_n21(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Defect): Defect {
    return from_candid_record_n22(uploadFile, downloadFile, value);
}
async function from_candid_ExternalBlob_n39(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ExternalBlob): Promise<ExternalBlob> {
    return await downloadFile(value);
}
async function from_candid_InspectionPhoto_n37(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _InspectionPhoto): Promise<InspectionPhoto> {
    return await from_candid_record_n38(uploadFile, downloadFile, value);
}
function from_candid_InspectionStatus_n27(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _InspectionStatus): InspectionStatus {
    return from_candid_variant_n28(uploadFile, downloadFile, value);
}
async function from_candid_Inspection_n25(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Inspection): Promise<Inspection> {
    return await from_candid_record_n26(uploadFile, downloadFile, value);
}
async function from_candid_Room_n34(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Room): Promise<Room> {
    return await from_candid_record_n35(uploadFile, downloadFile, value);
}
function from_candid_StripeSessionStatus_n43(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _StripeSessionStatus): StripeSessionStatus {
    return from_candid_variant_n44(uploadFile, downloadFile, value);
}
function from_candid_SubscriptionTier_n30(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _SubscriptionTier): SubscriptionTier {
    return from_candid_variant_n31(uploadFile, downloadFile, value);
}
function from_candid_UserProfile_n15(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserProfile): UserProfile {
    return from_candid_record_n16(uploadFile, downloadFile, value);
}
function from_candid_UserRole_n18(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n19(uploadFile, downloadFile, value);
}
function from_candid__CaffeineStorageRefillResult_n4(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: __CaffeineStorageRefillResult): _CaffeineStorageRefillResult {
    return from_candid_record_n5(uploadFile, downloadFile, value);
}
function from_candid_opt_n14(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : from_candid_UserProfile_n15(uploadFile, downloadFile, value[0]);
}
function from_candid_opt_n17(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
async function from_candid_opt_n24(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Inspection]): Promise<Inspection | null> {
    return value.length === 0 ? null : await from_candid_Inspection_n25(uploadFile, downloadFile, value[0]);
}
function from_candid_opt_n29(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Time]): Time | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n32(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_PropertyDetails]): PropertyDetails | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n6(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [boolean]): boolean | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n7(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n16(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    contactInfo: string;
    name: string;
    email: string;
    companyLogo: [] | [string];
    companyName: string;
}): {
    contactInfo: string;
    name: string;
    email: string;
    companyLogo?: string;
    companyName: string;
} {
    return {
        contactInfo: value.contactInfo,
        name: value.name,
        email: value.email,
        companyLogo: record_opt_to_undefined(from_candid_opt_n17(uploadFile, downloadFile, value.companyLogo)),
        companyName: value.companyName
    };
}
function from_candid_record_n22(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    recommendations: Array<[] | [string]>;
    description: string;
    severity: string;
    imageId: string;
}): {
    id: string;
    recommendations: Array<string | null>;
    description: string;
    severity: string;
    imageId: string;
} {
    return {
        id: value.id,
        recommendations: from_candid_vec_n23(uploadFile, downloadFile, value.recommendations),
        description: value.description,
        severity: value.severity,
        imageId: value.imageId
    };
}
async function from_candid_record_n26(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    startTime: _Time;
    status: _InspectionStatus;
    endTime: [] | [_Time];
    subscriptionTier: _SubscriptionTier;
    inspectorId: Principal;
    propertyDetails: [] | [_PropertyDetails];
    summary: string;
    address: _Address;
    aiAnalysisOngoing: boolean;
    rooms: Array<_Room>;
}): Promise<{
    id: string;
    startTime: Time;
    status: InspectionStatus;
    endTime?: Time;
    subscriptionTier: SubscriptionTier;
    inspectorId: Principal;
    propertyDetails?: PropertyDetails;
    summary: string;
    address: Address;
    aiAnalysisOngoing: boolean;
    rooms: Array<Room>;
}> {
    return {
        id: value.id,
        startTime: value.startTime,
        status: from_candid_InspectionStatus_n27(uploadFile, downloadFile, value.status),
        endTime: record_opt_to_undefined(from_candid_opt_n29(uploadFile, downloadFile, value.endTime)),
        subscriptionTier: from_candid_SubscriptionTier_n30(uploadFile, downloadFile, value.subscriptionTier),
        inspectorId: value.inspectorId,
        propertyDetails: record_opt_to_undefined(from_candid_opt_n32(uploadFile, downloadFile, value.propertyDetails)),
        summary: value.summary,
        address: value.address,
        aiAnalysisOngoing: value.aiAnalysisOngoing,
        rooms: await from_candid_vec_n33(uploadFile, downloadFile, value.rooms)
    };
}
async function from_candid_record_n35(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    name: string;
    defects: Array<_Defect>;
    photos: Array<_InspectionPhoto>;
}): Promise<{
    id: string;
    name: string;
    defects: Array<Defect>;
    photos: Array<InspectionPhoto>;
}> {
    return {
        id: value.id,
        name: value.name,
        defects: from_candid_vec_n20(uploadFile, downloadFile, value.defects),
        photos: await from_candid_vec_n36(uploadFile, downloadFile, value.photos)
    };
}
async function from_candid_record_n38(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    externalBlob: _ExternalBlob;
    annotations: Array<_Annotation>;
    aiAnalysisResults: Array<_AIAnalysisResult>;
    aiCaption: [] | [string];
    defectDescription: [] | [string];
}): Promise<{
    id: string;
    externalBlob: ExternalBlob;
    annotations: Array<Annotation>;
    aiAnalysisResults: Array<AIAnalysisResult>;
    aiCaption?: string;
    defectDescription?: string;
}> {
    return {
        id: value.id,
        externalBlob: await from_candid_ExternalBlob_n39(uploadFile, downloadFile, value.externalBlob),
        annotations: from_candid_vec_n40(uploadFile, downloadFile, value.annotations),
        aiAnalysisResults: value.aiAnalysisResults,
        aiCaption: record_opt_to_undefined(from_candid_opt_n17(uploadFile, downloadFile, value.aiCaption)),
        defectDescription: record_opt_to_undefined(from_candid_opt_n17(uploadFile, downloadFile, value.defectDescription))
    };
}
function from_candid_record_n42(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    color: string;
    text: [] | [string];
    timestamp: bigint;
    annotationType: string;
    coordinates: Array<bigint>;
}): {
    id: bigint;
    color: string;
    text?: string;
    timestamp: bigint;
    annotationType: string;
    coordinates: Array<bigint>;
} {
    return {
        id: value.id,
        color: value.color,
        text: record_opt_to_undefined(from_candid_opt_n17(uploadFile, downloadFile, value.text)),
        timestamp: value.timestamp,
        annotationType: value.annotationType,
        coordinates: value.coordinates
    };
}
function from_candid_record_n45(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    userPrincipal: [] | [string];
    response: string;
}): {
    userPrincipal?: string;
    response: string;
} {
    return {
        userPrincipal: record_opt_to_undefined(from_candid_opt_n17(uploadFile, downloadFile, value.userPrincipal)),
        response: value.response
    };
}
function from_candid_record_n5(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    success: [] | [boolean];
    topped_up_amount: [] | [bigint];
}): {
    success?: boolean;
    topped_up_amount?: bigint;
} {
    return {
        success: record_opt_to_undefined(from_candid_opt_n6(uploadFile, downloadFile, value.success)),
        topped_up_amount: record_opt_to_undefined(from_candid_opt_n7(uploadFile, downloadFile, value.topped_up_amount))
    };
}
function from_candid_variant_n19(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_variant_n28(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    completed: null;
} | {
    draft: null;
} | {
    inProgress: null;
} | {
    reportGenerated: null;
}): InspectionStatus {
    return "completed" in value ? InspectionStatus.completed : "draft" in value ? InspectionStatus.draft : "inProgress" in value ? InspectionStatus.inProgress : "reportGenerated" in value ? InspectionStatus.reportGenerated : value;
}
function from_candid_variant_n31(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    premium: null;
} | {
    free: null;
}): SubscriptionTier {
    return "premium" in value ? SubscriptionTier.premium : "free" in value ? SubscriptionTier.free : value;
}
function from_candid_variant_n44(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    completed: {
        userPrincipal: [] | [string];
        response: string;
    };
} | {
    failed: {
        error: string;
    };
}): {
    __kind__: "completed";
    completed: {
        userPrincipal?: string;
        response: string;
    };
} | {
    __kind__: "failed";
    failed: {
        error: string;
    };
} {
    return "completed" in value ? {
        __kind__: "completed",
        completed: from_candid_record_n45(uploadFile, downloadFile, value.completed)
    } : "failed" in value ? {
        __kind__: "failed",
        failed: value.failed
    } : value;
}
function from_candid_vec_n20(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Defect>): Array<Defect> {
    return value.map((x)=>from_candid_Defect_n21(uploadFile, downloadFile, x));
}
function from_candid_vec_n23(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<[] | [string]>): Array<string | null> {
    return value.map((x)=>from_candid_opt_n17(uploadFile, downloadFile, x));
}
async function from_candid_vec_n33(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Room>): Promise<Array<Room>> {
    return await Promise.all(value.map(async (x)=>await from_candid_Room_n34(uploadFile, downloadFile, x)));
}
async function from_candid_vec_n36(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_InspectionPhoto>): Promise<Array<InspectionPhoto>> {
    return await Promise.all(value.map(async (x)=>await from_candid_InspectionPhoto_n37(uploadFile, downloadFile, x)));
}
function from_candid_vec_n40(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Annotation>): Array<Annotation> {
    return value.map((x)=>from_candid_Annotation_n41(uploadFile, downloadFile, x));
}
function to_candid_DefectInput_n48(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: DefectInput): _DefectInput {
    return to_candid_record_n49(uploadFile, downloadFile, value);
}
function to_candid_Defect_n50(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Defect): _Defect {
    return to_candid_record_n51(uploadFile, downloadFile, value);
}
async function to_candid_ExternalBlob_n54(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ExternalBlob): Promise<_ExternalBlob> {
    return await uploadFile(value);
}
function to_candid_InspectionInput_n10(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: InspectionInput): _InspectionInput {
    return to_candid_record_n11(uploadFile, downloadFile, value);
}
function to_candid_SubscriptionTier_n12(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: SubscriptionTier): _SubscriptionTier {
    return to_candid_variant_n13(uploadFile, downloadFile, value);
}
function to_candid_UserProfile_n46(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserProfile): _UserProfile {
    return to_candid_record_n47(uploadFile, downloadFile, value);
}
function to_candid_UserRole_n8(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n9(uploadFile, downloadFile, value);
}
function to_candid__CaffeineStorageRefillInformation_n2(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation): __CaffeineStorageRefillInformation {
    return to_candid_record_n3(uploadFile, downloadFile, value);
}
function to_candid_opt_n1(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation | null): [] | [__CaffeineStorageRefillInformation] {
    return value === null ? candid_none() : candid_some(to_candid__CaffeineStorageRefillInformation_n2(uploadFile, downloadFile, value));
}
function to_candid_opt_n53(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: string | null): [] | [string] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_record_n11(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    tier: SubscriptionTier;
    inspectorId: Principal;
    propertyDetails?: PropertyDetails;
    address: Address;
}): {
    tier: _SubscriptionTier;
    inspectorId: Principal;
    propertyDetails: [] | [_PropertyDetails];
    address: _Address;
} {
    return {
        tier: to_candid_SubscriptionTier_n12(uploadFile, downloadFile, value.tier),
        inspectorId: value.inspectorId,
        propertyDetails: value.propertyDetails ? candid_some(value.propertyDetails) : candid_none(),
        address: value.address
    };
}
function to_candid_record_n3(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    proposed_top_up_amount?: bigint;
}): {
    proposed_top_up_amount: [] | [bigint];
} {
    return {
        proposed_top_up_amount: value.proposed_top_up_amount ? candid_some(value.proposed_top_up_amount) : candid_none()
    };
}
function to_candid_record_n47(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    contactInfo: string;
    name: string;
    email: string;
    companyLogo?: string;
    companyName: string;
}): {
    contactInfo: string;
    name: string;
    email: string;
    companyLogo: [] | [string];
    companyName: string;
} {
    return {
        contactInfo: value.contactInfo,
        name: value.name,
        email: value.email,
        companyLogo: value.companyLogo ? candid_some(value.companyLogo) : candid_none(),
        companyName: value.companyName
    };
}
function to_candid_record_n49(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    defect: Defect;
    roomId: string;
}): {
    defect: _Defect;
    roomId: string;
} {
    return {
        defect: to_candid_Defect_n50(uploadFile, downloadFile, value.defect),
        roomId: value.roomId
    };
}
function to_candid_record_n51(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    recommendations: Array<string | null>;
    description: string;
    severity: string;
    imageId: string;
}): {
    id: string;
    recommendations: Array<[] | [string]>;
    description: string;
    severity: string;
    imageId: string;
} {
    return {
        id: value.id,
        recommendations: to_candid_vec_n52(uploadFile, downloadFile, value.recommendations),
        description: value.description,
        severity: value.severity,
        imageId: value.imageId
    };
}
function to_candid_variant_n13(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: SubscriptionTier): {
    premium: null;
} | {
    free: null;
} {
    return value == SubscriptionTier.premium ? {
        premium: null
    } : value == SubscriptionTier.free ? {
        free: null
    } : value;
}
function to_candid_variant_n9(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
function to_candid_vec_n52(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<string | null>): Array<[] | [string]> {
    return value.map((x)=>to_candid_opt_n53(uploadFile, downloadFile, x));
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, uploadFile, downloadFile, options.processError);
}
