/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0-beta.9.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const RoomInput = IDL.Record({
  'roomId' : IDL.Text,
  'inspectionId' : IDL.Text,
  'roomName' : IDL.Text,
});
export const AIAnalysisResult = IDL.Record({
  'defectType' : IDL.Text,
  'description' : IDL.Text,
  'severityRating' : IDL.Text,
  'confidence' : IDL.Text,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const ShoppingItem = IDL.Record({
  'productName' : IDL.Text,
  'currency' : IDL.Text,
  'quantity' : IDL.Nat,
  'priceInCents' : IDL.Nat,
  'productDescription' : IDL.Text,
});
export const SubscriptionTier = IDL.Variant({
  'premium' : IDL.Null,
  'free' : IDL.Null,
});
export const PropertyDetails = IDL.Record({
  'bedrooms' : IDL.Nat,
  'squareFootage' : IDL.Nat,
  'bathrooms' : IDL.Nat,
  'yearBuilt' : IDL.Nat,
});
export const Address = IDL.Record({
  'zip' : IDL.Text,
  'street' : IDL.Text,
  'city' : IDL.Text,
  'state' : IDL.Text,
});
export const InspectionInput = IDL.Record({
  'tier' : SubscriptionTier,
  'inspectorId' : IDL.Principal,
  'propertyDetails' : IDL.Opt(PropertyDetails),
  'address' : Address,
});
export const UserProfile = IDL.Record({
  'contactInfo' : IDL.Text,
  'name' : IDL.Text,
  'email' : IDL.Text,
  'companyLogo' : IDL.Opt(IDL.Text),
  'companyName' : IDL.Text,
});
export const Defect = IDL.Record({
  'id' : IDL.Text,
  'recommendations' : IDL.Vec(IDL.Opt(IDL.Text)),
  'description' : IDL.Text,
  'severity' : IDL.Text,
  'imageId' : IDL.Text,
});
export const Time = IDL.Int;
export const InspectionStatus = IDL.Variant({
  'completed' : IDL.Null,
  'draft' : IDL.Null,
  'inProgress' : IDL.Null,
  'reportGenerated' : IDL.Null,
});
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const Annotation = IDL.Record({
  'id' : IDL.Nat,
  'color' : IDL.Text,
  'text' : IDL.Opt(IDL.Text),
  'timestamp' : IDL.Int,
  'annotationType' : IDL.Text,
  'coordinates' : IDL.Vec(IDL.Int),
});
export const InspectionPhoto = IDL.Record({
  'id' : IDL.Text,
  'externalBlob' : ExternalBlob,
  'annotations' : IDL.Vec(Annotation),
  'aiAnalysisResults' : IDL.Vec(AIAnalysisResult),
  'aiCaption' : IDL.Opt(IDL.Text),
  'defectDescription' : IDL.Opt(IDL.Text),
});
export const Room = IDL.Record({
  'id' : IDL.Text,
  'name' : IDL.Text,
  'defects' : IDL.Vec(Defect),
  'photos' : IDL.Vec(InspectionPhoto),
});
export const Inspection = IDL.Record({
  'id' : IDL.Text,
  'startTime' : Time,
  'status' : InspectionStatus,
  'endTime' : IDL.Opt(Time),
  'subscriptionTier' : SubscriptionTier,
  'inspectorId' : IDL.Principal,
  'propertyDetails' : IDL.Opt(PropertyDetails),
  'summary' : IDL.Text,
  'address' : Address,
  'aiAnalysisOngoing' : IDL.Bool,
  'rooms' : IDL.Vec(Room),
});
export const StripeSessionStatus = IDL.Variant({
  'completed' : IDL.Record({
    'userPrincipal' : IDL.Opt(IDL.Text),
    'response' : IDL.Text,
  }),
  'failed' : IDL.Record({ 'error' : IDL.Text }),
});
export const StripeConfiguration = IDL.Record({
  'allowedCountries' : IDL.Vec(IDL.Text),
  'secretKey' : IDL.Text,
});
export const http_header = IDL.Record({
  'value' : IDL.Text,
  'name' : IDL.Text,
});
export const http_request_result = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});
export const TransformationInput = IDL.Record({
  'context' : IDL.Vec(IDL.Nat8),
  'response' : http_request_result,
});
export const TransformationOutput = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});
export const DefectInput = IDL.Record({
  'defect' : Defect,
  'roomId' : IDL.Text,
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  'addRoomToInspection' : IDL.Func([RoomInput], [], []),
  'analyzePhoto' : IDL.Func([IDL.Text, IDL.Text], [AIAnalysisResult], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createCheckoutSession' : IDL.Func(
      [IDL.Vec(ShoppingItem), IDL.Text, IDL.Text],
      [IDL.Text],
      [],
    ),
  'createInspection' : IDL.Func([InspectionInput], [IDL.Text], []),
  'deleteDefect' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getDefectsForRoom' : IDL.Func([IDL.Text], [IDL.Vec(Defect)], ['query']),
  'getInspection' : IDL.Func([IDL.Text], [IDL.Opt(Inspection)], ['query']),
  'getPropertyDetails' : IDL.Func(
      [IDL.Text],
      [IDL.Opt(PropertyDetails)],
      ['query'],
    ),
  'getRoom' : IDL.Func([IDL.Text], [Room], ['query']),
  'getRoomsWithPhotos' : IDL.Func([IDL.Text], [IDL.Vec(Room)], ['query']),
  'getRoomsWithoutPhotos' : IDL.Func([IDL.Text], [IDL.Vec(Room)], ['query']),
  'getStats' : IDL.Func([], [IDL.Vec(IDL.Tuple(IDL.Text, IDL.Nat))], ['query']),
  'getStripeSessionStatus' : IDL.Func([IDL.Text], [StripeSessionStatus], []),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'initializeAccessControl' : IDL.Func([], [], []),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'isStripeConfigured' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'setStripeConfiguration' : IDL.Func([StripeConfiguration], [], []),
  'transform' : IDL.Func(
      [TransformationInput],
      [TransformationOutput],
      ['query'],
    ),
  'updateDefect' : IDL.Func([DefectInput], [], []),
  'uploadPhoto' : IDL.Func([IDL.Text, IDL.Text, ExternalBlob], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const RoomInput = IDL.Record({
    'roomId' : IDL.Text,
    'inspectionId' : IDL.Text,
    'roomName' : IDL.Text,
  });
  const AIAnalysisResult = IDL.Record({
    'defectType' : IDL.Text,
    'description' : IDL.Text,
    'severityRating' : IDL.Text,
    'confidence' : IDL.Text,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const ShoppingItem = IDL.Record({
    'productName' : IDL.Text,
    'currency' : IDL.Text,
    'quantity' : IDL.Nat,
    'priceInCents' : IDL.Nat,
    'productDescription' : IDL.Text,
  });
  const SubscriptionTier = IDL.Variant({
    'premium' : IDL.Null,
    'free' : IDL.Null,
  });
  const PropertyDetails = IDL.Record({
    'bedrooms' : IDL.Nat,
    'squareFootage' : IDL.Nat,
    'bathrooms' : IDL.Nat,
    'yearBuilt' : IDL.Nat,
  });
  const Address = IDL.Record({
    'zip' : IDL.Text,
    'street' : IDL.Text,
    'city' : IDL.Text,
    'state' : IDL.Text,
  });
  const InspectionInput = IDL.Record({
    'tier' : SubscriptionTier,
    'inspectorId' : IDL.Principal,
    'propertyDetails' : IDL.Opt(PropertyDetails),
    'address' : Address,
  });
  const UserProfile = IDL.Record({
    'contactInfo' : IDL.Text,
    'name' : IDL.Text,
    'email' : IDL.Text,
    'companyLogo' : IDL.Opt(IDL.Text),
    'companyName' : IDL.Text,
  });
  const Defect = IDL.Record({
    'id' : IDL.Text,
    'recommendations' : IDL.Vec(IDL.Opt(IDL.Text)),
    'description' : IDL.Text,
    'severity' : IDL.Text,
    'imageId' : IDL.Text,
  });
  const Time = IDL.Int;
  const InspectionStatus = IDL.Variant({
    'completed' : IDL.Null,
    'draft' : IDL.Null,
    'inProgress' : IDL.Null,
    'reportGenerated' : IDL.Null,
  });
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const Annotation = IDL.Record({
    'id' : IDL.Nat,
    'color' : IDL.Text,
    'text' : IDL.Opt(IDL.Text),
    'timestamp' : IDL.Int,
    'annotationType' : IDL.Text,
    'coordinates' : IDL.Vec(IDL.Int),
  });
  const InspectionPhoto = IDL.Record({
    'id' : IDL.Text,
    'externalBlob' : ExternalBlob,
    'annotations' : IDL.Vec(Annotation),
    'aiAnalysisResults' : IDL.Vec(AIAnalysisResult),
    'aiCaption' : IDL.Opt(IDL.Text),
    'defectDescription' : IDL.Opt(IDL.Text),
  });
  const Room = IDL.Record({
    'id' : IDL.Text,
    'name' : IDL.Text,
    'defects' : IDL.Vec(Defect),
    'photos' : IDL.Vec(InspectionPhoto),
  });
  const Inspection = IDL.Record({
    'id' : IDL.Text,
    'startTime' : Time,
    'status' : InspectionStatus,
    'endTime' : IDL.Opt(Time),
    'subscriptionTier' : SubscriptionTier,
    'inspectorId' : IDL.Principal,
    'propertyDetails' : IDL.Opt(PropertyDetails),
    'summary' : IDL.Text,
    'address' : Address,
    'aiAnalysisOngoing' : IDL.Bool,
    'rooms' : IDL.Vec(Room),
  });
  const StripeSessionStatus = IDL.Variant({
    'completed' : IDL.Record({
      'userPrincipal' : IDL.Opt(IDL.Text),
      'response' : IDL.Text,
    }),
    'failed' : IDL.Record({ 'error' : IDL.Text }),
  });
  const StripeConfiguration = IDL.Record({
    'allowedCountries' : IDL.Vec(IDL.Text),
    'secretKey' : IDL.Text,
  });
  const http_header = IDL.Record({ 'value' : IDL.Text, 'name' : IDL.Text });
  const http_request_result = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  const TransformationInput = IDL.Record({
    'context' : IDL.Vec(IDL.Nat8),
    'response' : http_request_result,
  });
  const TransformationOutput = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  const DefectInput = IDL.Record({ 'defect' : Defect, 'roomId' : IDL.Text });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    'addRoomToInspection' : IDL.Func([RoomInput], [], []),
    'analyzePhoto' : IDL.Func([IDL.Text, IDL.Text], [AIAnalysisResult], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createCheckoutSession' : IDL.Func(
        [IDL.Vec(ShoppingItem), IDL.Text, IDL.Text],
        [IDL.Text],
        [],
      ),
    'createInspection' : IDL.Func([InspectionInput], [IDL.Text], []),
    'deleteDefect' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getDefectsForRoom' : IDL.Func([IDL.Text], [IDL.Vec(Defect)], ['query']),
    'getInspection' : IDL.Func([IDL.Text], [IDL.Opt(Inspection)], ['query']),
    'getPropertyDetails' : IDL.Func(
        [IDL.Text],
        [IDL.Opt(PropertyDetails)],
        ['query'],
      ),
    'getRoom' : IDL.Func([IDL.Text], [Room], ['query']),
    'getRoomsWithPhotos' : IDL.Func([IDL.Text], [IDL.Vec(Room)], ['query']),
    'getRoomsWithoutPhotos' : IDL.Func([IDL.Text], [IDL.Vec(Room)], ['query']),
    'getStats' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(IDL.Text, IDL.Nat))],
        ['query'],
      ),
    'getStripeSessionStatus' : IDL.Func([IDL.Text], [StripeSessionStatus], []),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'initializeAccessControl' : IDL.Func([], [], []),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'isStripeConfigured' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'setStripeConfiguration' : IDL.Func([StripeConfiguration], [], []),
    'transform' : IDL.Func(
        [TransformationInput],
        [TransformationOutput],
        ['query'],
      ),
    'updateDefect' : IDL.Func([DefectInput], [], []),
    'uploadPhoto' : IDL.Func([IDL.Text, IDL.Text, ExternalBlob], [], []),
  });
};

export const init = ({ IDL }) => { return []; };