/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0-beta.9.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface AIAnalysisResult {
  'defectType' : string,
  'description' : string,
  'severityRating' : string,
  'confidence' : string,
}
export interface Address {
  'zip' : string,
  'street' : string,
  'city' : string,
  'state' : string,
}
export interface Annotation {
  'id' : bigint,
  'color' : string,
  'text' : [] | [string],
  'timestamp' : bigint,
  'annotationType' : string,
  'coordinates' : Array<bigint>,
}
export interface Defect {
  'id' : string,
  'recommendations' : Array<[] | [string]>,
  'description' : string,
  'severity' : string,
  'imageId' : string,
}
export interface DefectInput { 'defect' : Defect, 'roomId' : string }
export type ExternalBlob = Uint8Array;
export interface Inspection {
  'id' : string,
  'startTime' : Time,
  'status' : InspectionStatus,
  'endTime' : [] | [Time],
  'subscriptionTier' : SubscriptionTier,
  'inspectorId' : Principal,
  'propertyDetails' : [] | [PropertyDetails],
  'summary' : string,
  'address' : Address,
  'aiAnalysisOngoing' : boolean,
  'rooms' : Array<Room>,
}
export interface InspectionInput {
  'tier' : SubscriptionTier,
  'inspectorId' : Principal,
  'propertyDetails' : [] | [PropertyDetails],
  'address' : Address,
}
export interface InspectionPhoto {
  'id' : string,
  'externalBlob' : ExternalBlob,
  'annotations' : Array<Annotation>,
  'aiAnalysisResults' : Array<AIAnalysisResult>,
  'aiCaption' : [] | [string],
  'defectDescription' : [] | [string],
}
export type InspectionStatus = { 'completed' : null } |
  { 'draft' : null } |
  { 'inProgress' : null } |
  { 'reportGenerated' : null };
export interface PropertyDetails {
  'bedrooms' : bigint,
  'squareFootage' : bigint,
  'bathrooms' : bigint,
  'yearBuilt' : bigint,
}
export interface Room {
  'id' : string,
  'name' : string,
  'defects' : Array<Defect>,
  'photos' : Array<InspectionPhoto>,
}
export interface RoomInput {
  'roomId' : string,
  'inspectionId' : string,
  'roomName' : string,
}
export interface ShoppingItem {
  'productName' : string,
  'currency' : string,
  'quantity' : bigint,
  'priceInCents' : bigint,
  'productDescription' : string,
}
export interface StripeConfiguration {
  'allowedCountries' : Array<string>,
  'secretKey' : string,
}
export type StripeSessionStatus = {
    'completed' : { 'userPrincipal' : [] | [string], 'response' : string }
  } |
  { 'failed' : { 'error' : string } };
export type SubscriptionTier = { 'premium' : null } |
  { 'free' : null };
export type Time = bigint;
export interface TransformationInput {
  'context' : Uint8Array,
  'response' : http_request_result,
}
export interface TransformationOutput {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export interface UserProfile {
  'contactInfo' : string,
  'name' : string,
  'email' : string,
  'companyLogo' : [] | [string],
  'companyName' : string,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface http_header { 'value' : string, 'name' : string }
export interface http_request_result {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  'addRoomToInspection' : ActorMethod<[RoomInput], undefined>,
  'analyzePhoto' : ActorMethod<[string, string], AIAnalysisResult>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createCheckoutSession' : ActorMethod<
    [Array<ShoppingItem>, string, string],
    string
  >,
  'createInspection' : ActorMethod<[InspectionInput], string>,
  'deleteDefect' : ActorMethod<[string, string], undefined>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getDefectsForRoom' : ActorMethod<[string], Array<Defect>>,
  'getInspection' : ActorMethod<[string], [] | [Inspection]>,
  'getPropertyDetails' : ActorMethod<[string], [] | [PropertyDetails]>,
  'getRoom' : ActorMethod<[string], Room>,
  'getRoomsWithPhotos' : ActorMethod<[string], Array<Room>>,
  'getRoomsWithoutPhotos' : ActorMethod<[string], Array<Room>>,
  'getStats' : ActorMethod<[], Array<[string, bigint]>>,
  'getStripeSessionStatus' : ActorMethod<[string], StripeSessionStatus>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'initializeAccessControl' : ActorMethod<[], undefined>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'isStripeConfigured' : ActorMethod<[], boolean>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'setStripeConfiguration' : ActorMethod<[StripeConfiguration], undefined>,
  'transform' : ActorMethod<[TransformationInput], TransformationOutput>,
  'updateDefect' : ActorMethod<[DefectInput], undefined>,
  'uploadPhoto' : ActorMethod<[string, string, ExternalBlob], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];